FROM php:7.2-apache

MAINTAINER ChessKuo <gyc880323@gmail.com>

COPY src/index.php /var/www/html
COPY src/message.php /var/www/html
COPY src/flag.txt /

WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www/html & \
	usermod -G www-data root

EXPOSE 80